/** @type {import('jest').Config} */
export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/src/setupTests.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  transform: {
    '^.+\\.(ts|tsx)$': [
      'ts-jest',
      {
        tsconfig: {
          jsx: 'react-jsx',
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
        },
      },
    ],
  },
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.(ts|tsx)',
    '<rootDir>/src/**/*.(test|spec).(ts|tsx)',
  ],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '/build/',
    '/coverage/',
    '/backup/',
    '/archive/',
    '/legacy/',
    '/deprecated/',
    '/docs/archive/',
    '/docs/legacy/',
    '/docs/backup/',
    '/docs/deprecated/',
    '/android/',
    '/ios/',
    '/public/.*-debug\\.js$',
    '/public/.*-test\\.(js|html)$',
    '/public/horror-.*\\.(js|html)$',
    '/public/theme-.*\\.js$',
    '/public/test-.*\\.js$',
    '/public/instant-.*\\.js$',
    '/public/comprehensive-.*\\.js$',
    '/public/targeted-.*\\.js$',
    '/public/transparent-.*\\.js$',
    '/public/enhanced-.*\\.js$',
    '/public/console-.*\\.js$',
    '/public/background-.*\\.js$',
    '/public/final-.*\\.js$',
    '/public/simple-.*\\.js$',
    '/public/quote-.*\\.js$',
    '/public/mobile-nav-.*\\.js$',
    '\\.backup$',
    '\\.bak$',
    '\\.old$',
    '\\.temp$',
    '\\.tmp$',
  ],
  collectCoverageFrom: [
    'src/**/*.(ts|tsx)',
    '!src/**/*.d.ts',
    '!src/main.tsx',
    '!src/vite-env.d.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  extensionsToTreatAsEsm: ['.ts', '.tsx'],
  testTimeout: 10000,
};
