name: ✨ Prettier Check

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: prettier-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '22'
  NPM_CONFIG_PREFER_OFFLINE: true
  NPM_CONFIG_NO_AUDIT: true
  NPM_CONFIG_NO_FUND: true
  NPM_CONFIG_PROGRESS: false
  NPM_CONFIG_LOGLEVEL: error

jobs:
  prettier:
    name: ✨ Prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: ✨ Run Prettier check (npx)
        run: |
          npx --yes prettier@^3.3.3 --check .
